// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABBuai9jtEeDz_FSnPtPti7vdgqGkTWnM',
    appId: '1:185720929847:web:a35a60001c37766da689b2',
    messagingSenderId: '185720929847',
    projectId: 'flight-26834',
    authDomain: 'flight-26834.firebaseapp.com',
    storageBucket: 'flight-26834.firebasestorage.app',
    measurementId: 'G-PKMY8W4GPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxxSo2Tpug8WJgpkZ8SKghTZ1ZOef23iQ',
    appId: '1:185720929847:android:28ce2a8cfad8887aa689b2',
    messagingSenderId: '185720929847',
    projectId: 'flight-26834',
    storageBucket: 'flight-26834.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6Rlor3DgsdF3ktVOZLubapwnbCeklUyQ',
    appId: '1:185720929847:ios:af92fc7beda2efa6a689b2',
    messagingSenderId: '185720929847',
    projectId: 'flight-26834',
    storageBucket: 'flight-26834.firebasestorage.app',
    iosBundleId: 'com.example.flight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6Rlor3DgsdF3ktVOZLubapwnbCeklUyQ',
    appId: '1:185720929847:ios:af92fc7beda2efa6a689b2',
    messagingSenderId: '185720929847',
    projectId: 'flight-26834',
    storageBucket: 'flight-26834.firebasestorage.app',
    iosBundleId: 'com.example.flight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABBuai9jtEeDz_FSnPtPti7vdgqGkTWnM',
    appId: '1:185720929847:web:3fda3619c7bfc437a689b2',
    messagingSenderId: '185720929847',
    projectId: 'flight-26834',
    authDomain: 'flight-26834.firebaseapp.com',
    storageBucket: 'flight-26834.firebasestorage.app',
    measurementId: 'G-8H2GZM4VJL',
  );
}
